apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.consul}}
  name: {{.Values.edgex.app.core.consul}}
spec:
  ports:
  - name: "8400"
    port: 8400
    targetPort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
    nodePort: {{.Values.expose.nodePort.core.consul}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.core.consul}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
