apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
  name: {{.Values.edgex.app.support.notifications}}
spec:
  ports:
  - name: "48060"
    port: 48060
    targetPort: 48060
    nodePort: {{.Values.expose.nodePort.support.notifications}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
