apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  name: {{.Values.edgex.app.support.rulesengine}}
spec:
  ports:
  - name: "48075"
    port: 48075
    targetPort: 48075
    nodePort: {{.Values.expose.nodePort.support.rulesengine}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
