apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.redis}}
  name: {{.Values.edgex.app.redis}}
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.redis}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
