{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: redis-ha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-ha
subjects:
- kind: ServiceAccount
  name: {{ template "redis-ha.serviceAccountName" . }}
{{- end -}}
