apiVersion: v1
kind: Service
metadata:
  name: {{.Values.edgex.app.redis}}-sentinel
  labels:
    role: service
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-role: "sentinel"
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
