apiVersion: v1
kind: Service
metadata:
  name: {{.Values.edgex.app.redis}}-slave-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: "redis-ha"
    redis-node: "true"
    redis-role: "slave"
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
