apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-command
  name: edgex-core-command
spec:
  ports:
  - name: "48082"
    port: 48082
    targetPort: 48082
  selector:
    org.edgexfoundry.service: edgex-core-command
  type: LoadBalancer
status:
  loadBalancer: {}
