apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-device-virtual
  name: edgex-device-virtual
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-device-virtual
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-device-virtual
    spec:
      containers:
      - image: edgexfoundry/docker-device-virtual-go:1.1.1
        name: edgex-device-virtual
        ports:
        - containerPort: 49990
        resources: {}
      hostname: edgex-device-virtual
      restartPolicy: Always
status: {}
