apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
status: {}
