apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  name: {{.Values.edgex.app.appservice.rules}}
spec:
  replicas: {{.Values.edgex.replicas.appservice.rules}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  strategy: {}
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
    spec:
      containers:
      - name: {{.Values.edgex.app.appservice.rules}}
        image: {{.Values.edgex.image.appservice.rules.repository}}:{{.Values.edgex.image.appservice.rules.tag}}
        imagePullPolicy: {{.Values.edgex.image.appservice.rules.pullPolicy}}
        ports:
        - containerPort: 48100
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: edgex_profile
          value: "rules-engine"
        - name: Service_Host
          value: {{.Values.edgex.app.appservice.rules}}
        - name: Service_Port
          value: "48100"
        - name: MessageBus_SubscribeHost_Host
          value: {{.Values.edgex.app.core.data}}
        - name: Binding_PublishTopic
          value: "events"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48100
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48100
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.appservice.rules.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.appservice.rules.limits.memory }}
            cpu: {{ .Values.edgex.resources.appservice.rules.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.appservice.rules.requests.memory }}
            cpu: {{ .Values.edgex.resources.appservice.rules.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.appservice.rules}}
      restartPolicy: Always
status: {}
