apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-logging
  name: edgex-support-logging
spec:
  ports:
  - name: "48061"
    port: 48061
    targetPort: 48061
  selector:
    org.edgexfoundry.service: edgex-support-logging
status:
  loadBalancer: {}
