apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.notifications.name}}
  name: {{.Values.edgex.notifications.name}}
spec:
  ports:
  - name: "48060"
    port: 48060
    targetPort: 48060
  selector:
    org.edgexfoundry.service: {{.Values.edgex.notifications.name}}
status:
  loadBalancer: {}
