apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.system.name}}
  name: {{.Values.edgex.system.name}}
spec:
  ports:
  - name: "48090"
    port: 48090
    targetPort: 48090
  selector:
    org.edgexfoundry.service: {{.Values.edgex.system.name}}
  type: LoadBalancer
status:
  loadBalancer: {}
