apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-notifications
  name: edgex-support-notifications
spec:
  ports:
  - name: "48060"
    port: 48060
    targetPort: 48060
  selector:
    org.edgexfoundry.service: edgex-support-notifications
status:
  loadBalancer: {}
