apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-ui-go
  name: edgex-ui-go
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    org.edgexfoundry.service: edgex-ui-go
  type: LoadBalancer
status:
  loadBalancer: {}
