apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-mongo
  name: edgex-mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    org.edgexfoundry.service: edgex-mongo
  type: LoadBalancer
status:
  loadBalancer: {}
