apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-scheduler
  name: edgex-support-scheduler
spec:
  ports:
  - name: "48085"
    port: 48085
    targetPort: 48085
  selector:
    org.edgexfoundry.service: edgex-support-scheduler
status:
  loadBalancer: {}
