apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.metadata.name}}
  name: {{.Values.edgex.metadata.name}}
spec:
  ports:
  - name: "48081"
    port: 48081
    targetPort: 48081
  selector:
    org.edgexfoundry.service: {{.Values.edgex.metadata.name}}
  type: LoadBalancer
status:
  loadBalancer: {}
