apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
  name: {{.Values.edgex.app.device.virtual}}
spec:
  replicas: {{.Values.edgex.replicas.device.virtual}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
    spec:
      containers:
      - name: {{.Values.edgex.app.device.virtual}}
        image: {{.Values.edgex.image.device.virtual.repository}}:{{.Values.edgex.image.device.virtual.tag}}
        imagePullPolicy: {{.Values.edgex.image.device.virtual.pullPolicy}}
        ports:
        - containerPort: 49990
        env:
        - name: edgex_registry
          value: consul://{{.Values.edgex.app.core.consul}}:8500
        - name: Clients_Data_Host
          value: {{.Values.edgex.app.core.data}}
        - name: Clients_Metadata_Host
          value: {{.Values.edgex.app.core.metadata}}
        - name: Clients_Logging_Host
          value: {{.Values.edgex.app.support.logging}}
        - name: Logging_EnableRemote
          value: "false"
      {{- if .Values.edgex.resources.device.virtual.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.device.virtual.limits.memory }}
            cpu: {{ .Values.edgex.resources.device.virtual.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.device.virtual.requests.memory }}
            cpu: {{ .Values.edgex.resources.device.virtual.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.device.virtual}}
      restartPolicy: Always
status: {}
