apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.ui}}
  name: {{.Values.edgex.app.ui}}
spec:
  replicas: {{.Values.edgex.replicas.ui}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.ui}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.ui}}
    spec:
      containers:
      - name: {{.Values.edgex.app.ui}}
        image: {{.Values.edgex.image.ui.repository}}:{{.Values.edgex.image.ui.tag}}
        imagePullPolicy: {{.Values.edgex.image.ui.pullPolicy}}
        ports:
        - containerPort: 4000
        env:
        - name: Clients_CoreData_Host
          value: {{.Values.edgex.app.core.data}}
        - name: Clients_Metadata_Host
          value: {{.Values.edgex.app.core.metadata}}
        - name: Clients_CoreCommand_Host
          value: {{.Values.edgex.app.core.command}}
        - name: Clients_Notification_Host
          value: {{.Values.edgex.app.support.notifications}}
        - name: Clients_Scheduler_Host
          value: {{.Values.edgex.app.support.scheduler}}
        - name: Clients_RuleEngine_Host
          value: {{.Values.edgex.app.support.rulesengine}}
        - name: Registry_Host
          value: {{.Values.edgex.app.core.consul}}
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.ui.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.ui.limits.memory }}
            cpu: {{ .Values.edgex.resources.ui.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.ui.requests.memory }}
            cpu: {{ .Values.edgex.resources.ui.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.ui}}
      restartPolicy: Always
status: {}
