apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.ui.name}}
  name: {{.Values.edgex.ui.name}}
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    org.edgexfoundry.service: {{.Values.edgex.ui.name}}
  type: LoadBalancer
status:
  loadBalancer: {}
