apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.consul.name}}
  name: {{.Values.edgex.consul.name}}
spec:
  ports:
  - name: "8400"
    port: 8400
    targetPort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
  selector:
    org.edgexfoundry.service: {{.Values.edgex.consul.name}}
  type: LoadBalancer
status:
  loadBalancer: {}
