apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-rulesengine
  name: edgex-support-rulesengine
spec:
  ports:
  - name: "48075"
    port: 48075
    targetPort: 48075
  selector:
    org.edgexfoundry.service: edgex-support-rulesengine
status:
  loadBalancer: {}
